# -*- coding: utf-8 -*-
"""assignment2_dsml.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WXSHTAalsAyQQCBp9Ob8RRvLBok-Dj-L
"""

fruits=["Pineapple", "banana", "apple", "orange", "kiwi"]

fruits.append("grapes")

fruits

list = [1,2,3,4,5]

list.pop()
list

