# -*- coding: utf-8 -*-
"""assignment1_dsml.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ERMU0XA9XNwJSyC613PZKDuuwuADd88R
"""

a="my name is shradha"

a.lower()

a.upper()

a.capitalize()

a.title()

a.strip("a")

a.lstrip()

a.rstrip()

a.replace("a", "x")

a.split("a")

a.join(a)

a.find("a")

a.index("a")

a.find("b")

a.count("a")

a.startswith("a")

a.endswith("a")

a.isalnum()

a.isalpha()

a.isdigit()

a.isspace()

a.islower()

a.isupper()

word = "python"
word.isalpha()

