# -*- coding: utf-8 -*-
"""day35_dsml_data cleaning , chi sqr test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X9gwqa0XcJLRjYAhJHXi4aVkT_SLeRD4
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

titanic_df = pd.read_csv("/content/drive/MyDrive/dsml/titanic.csv")

titanic_df.head()

#renaming columns
#Pclass - Pstatus
#Sex - Gender

titanic_df.rename(columns={'Pclass':'Pstatus','Sex':'Gender'}, inplace=True)

titanic_df.head()

import numpy as np
data = pd.DataFrame({
    "id": [1,3,5,7,9],
    "name":["John", "Jane","Jennifer", "Johan", "Jeff"],
    "age": [25, -32, 19, 42, 55],
    "gender": ["M", "M", "Z", "F", "F"],
    "income" : [400, 700, 300, np.nan, 600]


})

data.dtypes

data["age"] = data["age"].abs()

data

filter_age = data[(data.age >= 18) & (data.age <= 45)]
filter_age

data[data.gender.isin(["M", "F"])]

#.isin() to filter to the data

data[data.name.isin(["John"])]

#saving a dataframe

titanic_df.to_csv("clean_data.csv", index = False)

data.to_json("clean_data.json", index = False, orient = "records")

"""chi-square test is a statistical test used in data science to determine whether there is"""

import pandas as pd

data = {
    "Gender": ["Male", "Male", "Male", "Female", "Female", "Female",
               "Male", "Female", "Male", "Female"],
    "Purchased": ["Yes", "No", "Yes", "No", "Yes", "No",
                  "Yes", "No", "Yes", "Yes"]
}

df = pd.DataFrame(data)

print(df)

contigency_table = pd.crosstab(df["Gender"], df["Purchased"])

contigency_table

from scipy.stats import chi2_contingency
chi2, p, dof, expected = chi2_contingency(contigency_table)

print("Chi-square value:", chi2)
print("P-value:", p)
print("Degrees of freedom:", dof)
print("Expected frequencies:\n", expected)

alpha = 0.05
if p< alpha:
  print("Reject the numm hypothesis")
else:
  print("Fail to reject the null hypothesis")

#degree of freedom = (rows -1 )* (columns -1)

"""missing data -
1. missing info
2. fill the gap

reason for misisng data -
1. natural causes
2. missing by design
3. non applicability
4. iten non response
5. data withholding
6. partial data avaulability
7. data rarity
8. logistic issues
9. technical malfunction
10. errorneous data collection
---------------------------------

implication of missing data:
1. unbalanced dataset


-----------------------------------


Handling missing data
1. Listwise deletion method

kunai row ma missing val cha bhane whole row hataidine

2. pairwise deletion

duita value ko correlation use garera data fill garcham missing values ma

3. dropping variables

whole column drop

4. single imputation- hot and cold deck

hot deck - same dataset bata halyo bhane hot deck
cold deck - external source bata lyaune
imputation ( data add garne technique)

5. single imputation - mean , median, mode

6. single imputation - last observed value

7. single imputation - linear interpolation

8. multiple imputation (mice procedure)

"""

