# -*- coding: utf-8 -*-
"""day26_dsml_numpy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZDUcHTSlC1NiNI6rk0G-0JhMdu4rc5Ad
"""

import numpy as np

#1D numpy

arr_1d = np.array([1,2,3,4,5])
print(arr_1d)

arr_1d = np.array([1,2,3,4,5.5])
print(arr_1d)

#2D numpy
arr_2d = np.array([[1,2,3,4,5], [3,4,5,6,7]])
print(arr_2d)

arr_2d.shape

#3D numpy
arr_nested = np.array([[[1,2,3,4,5], [3,4,5,6,7]], [[1,2,3,4,5], [3,4,5,6,7]]])
print(arr_nested)

arr_nested.shape

#list vs numpy array

#list
import time
start = time.time()
py_list = [i*2 for i  in range(100000000)]
print("\n List operation time:", time.time()-start)

#numpy
start = time.time()
np_array = np.arange(100000000)*2
print("\n Numpy operation time:", time.time()-start)

#list
py_list = [1,2,3]
print("Python list multiplication", py_list*3)

ny_array = np.array([1,2,3]) #element wise multiplication
print("Numpy array multiplcation:", ny_array*3) #3 is called scalar, we can perform the vector multiplication

#rank 0 (scalar)
a = np.array(10)
a.ndim

#rank 1 (vector)
a = np.array([1,2,3,4])
a.ndim

#rank 2 (matrix)
a = np.array([
    [1,2,3],
    [5,6,7]
])
a.ndim

a.shape

#classwork
#create the 5*5 matrix and see the rank
#rank, shape, ndim, create array

a5 = np.array([
     [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
    [21, 22, 23, 24, 25]
])
a5.ndim

a5.shape

ones = np.ones((5,5),dtype="int")
print(ones)

np.ones(shape =(4,5), dtype = "int8")

a = np.array([
    [1,2,3],
    [5,6,7]
])
print(a.sum(axis = 0)) #0= column

print(a. sum(axis = 1)) #1 = row

#random array
random = np.random.random((3,3))
print(random)

#full
full = np.full((5,2,4),9)
full

#linespace() - create evenly spaced values
arr = np.linspace(0,100,20)
arr

#diagnol matrix
arr = np.diag([1,2,3,4])
arr

#eye  - create matric with ones in diagnol
arr = np.eye(5)
print(arr)

arr = np.eye(3,4)

arr

# identity() - create identity matrix (always square matrix)

arr= np.identity(3)
arr

#create arr of random num
arr = np.random.rand(2,3)
arr

arr = np.arange(5)
arr

arr = np.arange(3,8, step=1) #3 = start- 8 = end
arr

"""class task"""

arr1d = np.array([10,20,30,40,50])
print(arr1d)

arr2d = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr2d)

zeros = np.zeros((3,4))
zeros

arr = np.arange(1,19, step=2)
arr

arr = np.linspace(0,100,5)
arr

