# -*- coding: utf-8 -*-
"""day30_dsml_exploration(pandas).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1369a9wP3autRKBjJ7tqd40DVk1K94dwN
"""

import pandas as pd

data = {
    "Age" : [25,30,35],
    "City": ["ktm", 'butwal', 'pkr']
}

df = pd.DataFrame(data, index = ['Ram', 'Shyam', 'Hari'])

df

df.loc['Ram']

df.loc['Hari']

df.loc["Shyam"]

#using loc : Target the row by its string name

df['Age'] #column wise

df.iloc[1]

#iloc - target the row by its numeric position (0 is first, 1 is second)

df.loc['Ram': 'Shyam']

df.iloc[0:2]

df.iloc[1:2]

#row and column selection combined

df.loc['Ram', 'City']

df.loc["Ram", "Age"]

#using iloc ; use integer indices for both dimension
df.iloc[0,1]

df.iloc[1,1]

from google.colab import drive
drive.mount('/content/drive')

titanic_df = pd.read_csv('/content/drive/MyDrive/dsml/titanic.csv')

titanic_df.shape

titanic_df.columns

titanic_df.head()

titanic_df.tail()

titanic_df

titanic_df.dtypes

titanic_df.info()

titanic_df[["Age", "Fare"]].mean()

titanic_df[["Age", "Fare"]].describe()

titanic_df.value_counts("Survived")

titanic_df["Sex"].value_counts()

titanic_df.value_counts(["Sex", "Survived"], ascending = True)

titanic_df.value_counts(["Sex", "Survived"], normalize = True, ascending = True)

titanic_df[titanic_df["Sex"]=="female"].value_counts("Survived", ascending = True, normalize = True)

titanic_df[titanic_df["Sex"]=="male"].value_counts("Survived", ascending = True, normalize = True)

titanic_df.value_counts("Embarked")

titanic_df[titanic_df["Embarked"]=="S"].value_counts("Sex")

titanic_df[(titanic_df["Embarked"]=="S" ) &(titanic_df["Sex"]=="male")]["Survived"].value_counts("Survived", "Sex")

titanic_df.value_counts(["Fare", "Survived"], normalize = True, ascending = True)

titanic_df.value_counts(["Pclass", "Survived"], normalize = True, ascending = True)

"""class task"""

df.columns = df.columns.str.strip()

df.columns

import numpy as np
import pandas as pd

fare_bins = [0, 50, 100, 300, 512]
fare_labels = ["Low Fare", "Medium Fare", "High Fare", "Very High Fare"]

titanic_df["FareGroup"] = pd.cut(
    titanic_df["Fare"],
    bins=fare_bins,
    labels=fare_labels,
    include_lowest=True
)

print(titanic_df[["Fare", "FareGroup"]].head())

#fare
titanic_df["FareClass"]  = pd.cut(
    titanic_df["Fare"], bins = [0,150,300,450,600], labels=["Low", "Medium", "High", "Very High"], right = True
)
titanic_df.value_counts(["FareClass", "Survived"], ascending = True)

