# -*- coding: utf-8 -*-
"""day6_dsml(tuple).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UlmBAM_REcaxR05KXUkLJPTiJuY8hnYg
"""

data = (1,2,3,4,5)

type(data)

data2 = [1,2,3,4,5]
type(data2)

data3 = tuple(data2)

type(data3)

num = (1,2,3,4,5,6)
type(num)

len(num)

max(num)

numbers = (-2, -5, 0 , 2)
print(any(x>0 for x in numbers))

numbers = (-2, -5, 0 , -1)
print(all(x>0 for x in numbers))

data_pack = 1, 2.0, 'three'
data_pack

a,b,c = data_pack
a

percentages = (80, 90, 95, 87, 55)
a,b,c,d,e = percentages
b

#indexing
t=(10,20,30)
print(t[1])

#slicing
t=(10,20,30,40)
print(t[1:3])

#concatenation
t1=(1,2)
t2=(3,4)
print(t1+t2)

#repititions
print(t*3)

#membership
t=(10,20,30,40,50)
print(20 in t)

#append, extend, del are not possible to use in tuple because they alter tuple

#set
data={1,2,3,4,5}
type(data)

data2={2,3,4,4,5,6,1,8}
data2

data3={}
type(data3)

a={1,2,3}
b={3,4,5}
print(a^b)

#subset
a={1,2,3,4,5}
b={1,2,3,4,5,6}
print(a <= b)

