# -*- coding: utf-8 -*-
"""day36_dsml_data integration encoding.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Fy6g9NOAU0CCp7bha6oSz0Cd5w_fvVw3
"""

#data concatenation

import pandas as pd

df1= pd.DataFrame({
    "acc" : [1,2,3],
    "name": ["Ram", "Shyam", "Hari"],
    "age": [2,3,4]

})

df1

df2 = pd.DataFrame({
    "acc":[5,6,7],
    "loan": [44, 55, 66],
})

df2

row_concat = pd.concat([df1, df2], axis = 0)

row_concat

column_concat = pd.concat([df1, df2], axis = 1)

column_concat

#merge
#merging is the process of combining two or more dataframes based on common columns

students = pd.DataFrame({
    "ID": [1,2,3],
    "Name": ["Ram", "Shyam", "Hari"],

})

marks = pd.DataFrame({
    "ID": [3,5,6],
    "Marks": [85, 90, 78]
})

result = pd.merge(students , marks, on = "ID", how = "inner")

result

result = pd.merge(students , marks, on = "ID", how = "outer")
result

result = pd.merge(students , marks, on = "ID", how = "left")

result

#join in pandas
#Joining is simlar to merging but specifically used to combine dataframes based on their indexes.
# we use pd.DataFrame.join() method to join dataframes

df1 = pd.DataFrame({
    "key": ["E", "B", "C", "Z"],
    "inv_val": [99,55,33,22],
    "acc":[1,2,5,7]

})

df1 = df1.set_index("key")

df1

df2 = pd.DataFrame({
    "key": ["A", "B", "C", "D"],
    "hel_ratio": [66,0.55,67,20],
    "acc":[11,32,53,74]

})

df2 = df2.set_index("key")

df2

df1.join(df2, how = "outer", lsuffix = "_x")

df2.join(df1, how = "right", rsuffix="_2")

"""*Stacking*


stacking is the process of vertically combining datasets with the same columns. The datasets are aligned by their column names and then stacked on top of each other. You can use the dataframe.stack() function to stack a dataframe
"""

df2 = pd.DataFrame({
    "key": ["A", "B", "C", "D"],
    "hel_ratio": [66,0.55,67,20],
    "acc":[11,32,53,74]

}
                   ,index = ["W", "X", "Y", "z"])

df2

stacked = df2.stack()
stacked

#Encoding

#data = categorical and numerical data

# label encoding
# one hot encoding

from google.colab import drive
drive.mount('/content/drive')

titanic_df = pd.read_csv("/content/drive/MyDrive/dsml/titanic.csv")

titanic_df["Sex"]

pd.get_dummies(titanic_df, columns = ["Sex"], dtype = int )

pd.get_dummies(titanic_df, columns = ["Embarked"], dtype = int )

