# -*- coding: utf-8 -*-
"""day20_abstract method.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WQi8ET1wIJsB9KcGj2viqVuSY9hiLY19
"""

class BankAccount:
  def __init__(self, name , balance , pin):
    self.name = name # public
    self._account_type = "Saving" #protected
    self._balance = balance # protected
    self.__pin = pin # private


  def get_balance(self,pin):
    if pin == self.__pin:
      return self._balance
    else:
      return "Incorrect Pin"


  def _update_balance(self, amount):
    self._balance += amount

class SavingAccount(BankAccount):
  def add_interest(self):
    balance = self.get_balance(self.user_pin)


    if isinstance(balance,(int, float)):
      interest = balance * 0.05
      self._update_balance(balance * 0.05)
      print(f"Interest added:{interest}")
    else:
      print("Not update balance:", balance)

name = input("Enter a name:")
balance = float(input("Enter your balance:"))
pin = int(input("Set a pin:"))

account = SavingAccount(name, balance, pin)
#store a pin
account.user_pin = pin

print("\n -- Account Details ---")
print("Account holder:", account.name)
print("Account type:", account._account_type)

account.add_interest()

enterd_pin = int(input("Enter your pin:"))
print("Balance:", account.get_balance(enterd_pin))

"""Abstract method"""

from abc import ABC, abstractmethod

# Abstract Class
class BankAccount(ABC):

    @abstractmethod
    def deposit(self, amount):
        pass

    @abstractmethod
    def withdraw(self, amount):
        pass

class SavingAccount(BankAccount):

    def __init__(self, balance):
        self.balance = balance

    def deposit(self, amount):
        self.balance += amount
        print("Deposited:", amount)
        print("Balance:", self.balance)

    def withdraw(self, amount):
        if amount <= self.balance:
            self.balance -= amount
            print("Withdrawn:", amount)
            print("Balance:", self.balance)
        else:
            print("Insufficient Balance")


# Driver Code
acc = SavingAccount(1000)

acc.deposit(500)
acc.withdraw(300)
acc.withdraw(1500)

