# -*- coding: utf-8 -*-
"""day19_dsml.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E5ueC0txM2TfhVZmc32ZHHIQocwqZM_A

Method overriding, encapsulation and abstraction
"""

class Parent:
  def myMethod(self):#instance method
    print("Calling parent method")

class Child(Parent):
  def myMethod(self):
    super().myMethod()
    print("Calling from child")

c = Child()
c.myMethod()

class Employee:
  def __init__(self, nm, sal):
    self.name = nm
    self.salary = sal

  def getName(self):  #camel case
    return self.name

  def getSalary(self):
    return self.salary

class Salesoffice(Employee):
  def __init__(self, nm , sal, inc):
    super().__init__(nm, sal)
    self.incnt = inc

  def getSalary(self):
    return self.salary + self.incnt

e1 = Employee("Shradha", 89000)
print("Total salary is {} in Rs{}".format(e1.getName(), e1.getSalary()))

s1 = Salesoffice("Ram", 76000, 10000)
print("Total salary is {} in Rs{}".format(s1.getName(), s1.getSalary()))

"""super()"""

class Example:
  def __init__(self):
    self.public_var = 1 #public var
    self.__private_var = 2 #private var
    self.protected_var = 3 #protected var


  def public_method(self):
    print("Public method")
    print("Private variable", self.__private_var)

  def _protected_method_convention(self):
    print("Protected method (by convention)")

  def __private_method_mangled(self):
    print("Private method (name-mangled)")

#creating object

obj = Example()

#accessing public members
print(obj.public_var)
obj.public_method()

# Accessing protected members (by convention)
# While accessible, direct access is generally discouraged outside the class.
print("Accessing _protected_method_convention:")
obj._protected_method_convention()

"""Class TAsk"""

class BankAccount:
    def __init__(self, name, balance):
        self.name = name
        self._account_type = "Bank"
        self.__balance = balance

    def deposit(self, amount):
      if amount>0:
        self.__balance += amount
        # Added print for deposit success, consistency with withdraw
        print(f"Deposited: {amount}")
      else:
        print("Invalid deposit amount")

    def withdraw(self, amount):
        if amount <= 0:
          print("Inavlid withdarwal amount")
        elif amount > self.__balance:
          print("Insufficient balance")
        else:
          self.__balance -= amount
          # Added print for withdraw success
          print(f"Withdrew: {amount}")

    def check_balance(self):
        # Changed to return the balance instead of just printing it
        return self.__balance

class SavingsAccount(BankAccount):
    def __init__(self, name, balance, rate):
        super().__init__(name, balance)
        self.rate = rate

    def add_interest(self):
        interest = self.check_balance() * self.rate / 100
        self.deposit(interest)


# Driver Code
acc = SavingsAccount("Ram", 10000, 5)

acc.deposit(1000)
acc.withdraw(2000)
# Now call check_balance and print its return value
print("Balance =", acc.check_balance())

acc.add_interest()
# Now call check_balance and print its return value
print("Balance after interest =", acc.check_balance())

from abc import ABC, abstractmethod

class Animal(ABC):
  @abstractmethod
  def make_sound(self):
    pass

class Dog(Animal): # Corrected: Dog is now a top-level class inheriting from Animal
  def make_sound(self):
    print("Woof!")

class Cat(Animal): # Corrected: Cat is now a top-level class inheriting from Animal
  def make_sound(self):
    print("Meow!")

dog = Dog()
dog.make_sound()

cat = Cat()
cat.make_sound()

"""Class Task"""

