# -*- coding: utf-8 -*-
"""day21_dsml_polymorphism.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IYgi6nPd-12uhdqdKLC9bpZzaTy3TGK2

Polymorphism
"""

#build in polymorphism

print(len("python"))

print(len([10,20,30]))

#runtime polymorphism

class PaymentGateway:
  def process_payment(self, amount):
    pass

class CreditCard(PaymentGateway):
  def process_payment(self, amount):
    return f"Processing ${amount} via Credit Card authentication."

class PayPal(PaymentGateway):
  def process_payment(self, amount):
    return f"Processing ${amount} via PayPal secure token."

# Unified interface function
def execute_checkout(payment_method, amount):
  print(payment_method.process_payment(amount))

# Usage
card = CreditCard()
wallet = PayPal()
execute_checkout(card, 250)
execute_checkout(wallet, 250)

#duck typing
class Duck:
  def swim(self):
    return "Duck swimming"

  def fly(self):
    return "Duck flying"

class Airplane:
  def fly(self):
    return "Airplane Fly"

def fly_test(entity):
  return entity.fly()

#create object
duck = Duck()
airplane = Airplane()

#same fucntion works with different objects
fly_test(duck)

fly_test(airplane)

"""Class task

Create classes esewa, khalti, and bankTransfer each having a pay (amount) method. Write a payment processor function that works with any payment method ovject
"""

class Esewa:
  def payment(self, amount):
    return f"Esewa paying:{amount}"

class Khalti:
  def payment(self,amount):
    return f"Khalti paying:{amount}"

class BankTransfer:
  def payment(self,amount):
    return f"BankTransfer paying:{amount}"

def pay_test_method(entity, amount):
  return entity.payment(amount)

e = Esewa()
k = Khalti()
b = BankTransfer()

pay_test_method(e, 250)

pay_test_method(k, 550)

pay_test_method(b, 1000)

#operator overloading
class Point:
  def __init__(self, x, y):
    self.x = x
    self.y = y

  def __str__(self):
    return f"({self.x},{self.y})"

  def __add__(self, other):
    x = self.x + other.x
    y = self.y + other.y
    return Point(x,y)

#create point objec
p1 = Point(1,2)
p2 = Point(3,4)

p3 = p1+ p2

print(p3)

import operator

a = 10
b = 5
print(operator.add(a,b))
print(operator.__add__(a,b))

class data:
  def physics(self):
    print("physics")

c = data()
c.physics()

a = 10
b = 15
print(a.__sub__(b))
print(a.__mul__(b))
print(a.__truediv__(b))

a= 50
b = 10
print(a.__floordiv__(b))

print(a.__mod__(b))

print(a.__pow__(b))

print(a.__eq__(b))

a.__lt__(b)

#subtraction
class Point:
  def __init__(self, x, y):
    self.x = x
    self.y = y

  def __str__(self):
    return f"({self.x},{self.y})"

  def __sub__(self, other):
    x = self.x - other.x
    y = self.y - other.y
    return Point(x,y)

p1 = Point(1,2)
p2 = Point(3,4)

p3 = p1 - p2
print(p3)

#multiply

class Point:
  def __init__(self, x, y):
    self.x = x
    self.y = y

  def __str__(self):
    return f"({self.x},{self.y})"

  def __mul__(self, other):
    x = self.x * other.x
    y = self.y * other.y
    return Point(x,y)

p1 = Point(2,4)
p2 = Point(3,2)

p3 = p1*p2
print(p3)

class Point:
  def __init__(self, x, y):
    self.x = x
    self.y = y

  def __str__(self):
    return f"({self.x},{self.y})"

  def __lshift__(self, other):
    x = self.x << other.x
    y = self.y << other.y
    return Point(x,y)

p1 = Point(2,3)
p2 = Point(4,5)

p3 = p1<<p3

print(p3)

"""Practise question

"""

