# -*- coding: utf-8 -*-
"""day34_dsml_penguin_csv.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iH62Izr-57PpyA2Dsd8fOS1wi1GjNkhb
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

titanic_df = pd.read_csv("/content/drive/MyDrive/dsml/titanic.csv")

titanic_df.head()

titanic_df.groupby(["Age", "Fare"])

titanic_df.groupby(["Fare", "Age"]).sum()

titanic_df.groupby("Sex")["Age"].transform("mean")

titanic_df.groupby("Age")["Fare"].transform("mean")

titles = titanic_df["Name"].str.split(",")
titanic_df["Title"] = titles.str[1].str.strip().str.split(' ').str[0]
titanic_df.head()

#cleaning duplicates
#printed duplicated values
titanic_df[titanic_df.duplicated(subset = "Sex")]

titanic_df.drop_duplicates(subset = "Sex", inplace = True)
titanic_df

#data management
#type conversion
#dataframe.astype()

titanic_df.dtypes

titanic_df.Pclass.astype("int8")

titanic_df_changed  = titanic_df.astype(
    {"Survived": bool, "Fare": int}
)
titanic_df_changed.head()

titanic_df.index = titanic_df.PassengerId.astype(str)+ "_skill"

titanic_df.index

titanic_df.head()

titanic_df.loc["1_skill"]

titanic_df = titanic_df.set_index("PassengerId")
titanic_df.head()

titanic_df.drop([2,5,8,66,300], axis =0 , inplace = True)

titanic_df

titanic_df.reset_index(drop = True)

#indexing = get index, set index, reset index

penguin_df = pd.read_csv("/content/drive/MyDrive/dsml/penguins.csv")

penguin_df.head()

penguin_df

penguin_df.isna()

penguin_df.isna().sum()

penguin_df.duplicated().sum()

bill_length_median = penguin_df.bill_length_mm.median()
bill_length_median

#median gives us a value closer to the typical observation.

penguin_df["bill_length_mm"].fillna(bill_length_median, inplace = True)

penguin_df["bill_depth_mm"] = penguin_df["bill_depth_mm"].fillna(penguin_df["bill_depth_mm"].median())

penguin_df["flipper_length_mm"]=penguin_df["flipper_length_mm"].fillna(penguin_df["flipper_length_mm"].median())

penguin_df["body_mass_g"] = penguin_df["body_mass_g"].fillna(penguin_df["body_mass_g"].median())

penguin_df.isna().sum()

#sex ia a categorcial value so we use mode

penguin_df["sex"] = penguin_df["sex"].fillna(penguin_df["sex"].mode()[0])

penguin_df.isna().sum()

penguin_df["species"].unique()

penguin_df["island"].unique()

penguin_df["sex"].unique()

penguin_df.dtypes

#making all the text consistent
penguin_df["species"] = penguin_df["species"].str.strip().str.title()

penguin_df["island"] = penguin_df["island"].str.strip().str.title()

penguin_df["sex"] = penguin_df["sex"].str.strip().str.title()

penguin_df

Q1 = titanic_df.Age.quantile(q=0.25)
Q3 = titanic_df.Age.quantile(q= 0.75)

IQR = Q3 - Q1
IQR

upper_limit =  Q3 + 1.5 * IQR
upper_limit

lower_limit = Q1 - 1.5 * IQR
lower_limit

titanic_df[(titanic_df.Age > upper_limit) | (titanic_df.Age< lower_limit)]

outlier_free = titanic_df[(titanic_df.Age < upper_limit) | (titanic_df.Age > lower_limit)]

outlier_free

outlier_free.Age.plot.box()

