# -*- coding: utf-8 -*-
"""day27_dsml_np_continue.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t3QrmijnPQ5ZazbniWIciWHNpyMXLVit
"""

import numpy as np

arr =np.array([
    [1,2,3],
    [5,6,7]
])

arr.shape

arr.ndim

arr.dtype

arr =np.array([
    [1,2,"data"],
    [5,6,7]
])

arr.shape

arr.dtype

arr = np.array(["apple", "banana", "watermelon"])
arr.dtype

"""Transpose"""

#array reshaping
arr = np.array([
    [1,2,3],
    [5,6,7]
])

#2*3 = 6 (1,6), (6,1)
reshaped_2d = arr.reshape(3,2)
reshaped_2d

arr = np.arange(10)
arr

reshaped = arr.reshape(2,5) #reshape le tuple ma value dincha
reshaped

reshaped.ndim

reshaped.shape

flattened = reshaped.flatten()
flattened

raveled = reshaped.ravel()
raveled

"""The primary difference between ravel() and flatten() in NumPy is that ravel() returns a view of the original array whenever possible, whereas flatten() always returns a new, independent copy of the data."""

arr =np.array([
    [1,2,3],
    [5,6,7]
])

transpose = arr.T
transpose

transpose.shape

#numpy array operation

#indexing and slicing

arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr[2:7])

#class task
arr = np.array([
    [1,2,3,5,7,5,8],
    [5,6,7,9,2,3,4]
])
print(arr[0:3, 1:4])

#arr[row_start:row_end, col_start:col_end]

arr = np.array([
    [10,20,30,40],
    [50,60,70,80],
    [90,100,110,120]
])

print(arr[1:3, 1:3])

#row only
print(arr[0:2])

print(arr[: :])

#first 2 rows
print(arr[:, 0:2])

#reverse rows
print(arr[::-1])

#reverse column
print(arr[:, ::-1])

#sorting
unsorted = np.array([2,5,4,3,6,8,0])
print(np.sort(unsorted))

arr = np.array([
    [4,2,6,8],
    [9,7,8,1]
])

print(np.sort(arr, axis=1))

print(np.sort(arr, axis=0))

#filter
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_number = numbers[numbers % 2 == 0]
print(even_number)

#filter with mask
mask = numbers > 5
print(numbers[mask])

numbers[numbers > 5] = 1000
print(numbers)

#np.where = returns index
where_result = np.where(numbers == 5)
print(where_result)
print("number where", numbers[where_result])

numbers = np.array([1,2,3,4,5,6,7,8,9,10])

conditional_array = np.where(numbers>5, numbers*4, numbers)
conditional_array

#adding data
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
add = arr1 + arr2
add

combine = np.concatenate((arr1, arr2))
combine

combine.shape

arr1.shape == arr2.shape

original = np.array([
    [1,2],
    [3,4]
])
new_row = np.array([5,6])

add_row = np.vstack((original, new_row))

add_row

#col
original = np.array([
    [1,2],
    [3,4]
])
new_col = np.array([[7], [8]])
add_col = np.hstack((original, new_col))
add_col

