# -*- coding: utf-8 -*-
"""day28_dsml_numpy_cont.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f8AoKkKcuJe10zU4FxZR4l8nxbf7SW24

element wise in matrix
"""

import numpy as np

matrix_1 = np.array([
    [1,2],
    [5,6]
])
matrix_1

matrix_2 = np.array([
    [4,6],
    [7,8]
])
matrix_2

#element wise addition
result = matrix_1 + matrix_2
result

#element wise subtraction
matrix_sub = matrix_1 - matrix_2
matrix_sub

#element wise multiplication
matrix_mul = matrix_1 * matrix_2
matrix_mul

#core matrix multiplication
result_mux = matrix_1 @ matrix_2
result_mux

result_mx = np.matmul(matrix_1,matrix_2)
result_mx

#element wise operations with scalars

print(matrix_1)
print("-----------------")
scalar = 2
result_add = matrix_1 + scalar
print(result_add)

#broadcasting in numpy

matrix_3 = np.array([
    [1,2],
    [3,4]
])
array_1 = np.array([5,6
])

#adding 1D and 2D matrix
result = matrix_3 + array_1
result

#computing the determinant
A = np.array([
    [1,2],
    [3,4]
])
det = np.linalg.det(A)
print(det)

#inverse
A_inv = np.linalg.inv(A)
print(A_inv)

print(A @ A_inv)

#linear algebra solve
a = np.array([
    [2 ,1],
    [1 ,3]
])

n = np.array([5,6])

X = np.linalg.solve(a,n)
X

#class task
a = np.array([
    [1,1,1],
    [2,5,1],
    [2,3,8]
])

b = np.array([6, -4, 5])

X = np.linalg.solve(a,b)
X

# y=mx+c
X = np.array([
    [1,1],
    [2,1],
    [3,1]
])

y = np.array([2,3,5])

beta = np.linalg.inv(X.T @ X) @ X.T @y
beta

print("slope m", beta[0])

print("intercept", beta[1])

