# -*- coding: utf-8 -*-
"""day18_dsml_oop.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/177_wWRvzU4TqNo07-36LhZ7FEGeRlCDJ
"""

class Animal:
  def sound(self): #instance method
    print("Animal makes sound")

class Dog(Animal):
  def bark(self):
    print("Dog barks")

d = Animal()
d.sound()

b = Dog()
b.sound()
b.bark()

"""multiple inheritance in python"""

class Flyer:
  def fly(self):
    print("I can fly")

class Swimmer:
  def swim(self):
    print("I can swim")

class Duck(Flyer, Swimmer):
  pass


donald = Duck()
donald.fly()

donald.swim()

"""Multilevel inheritance"""

class Grandparent:
  def house(self):
    print("Owns a house")

class Parent(Grandparent):
  def car(self):
    print("Owns a car")

class Child(Parent):
  def bike(self):
    print("owns a bike")

c= Child()
c.house()
c.car()
c.bike()

"""class task"""

class Person():
  def __init__(self, name, age, **kwargs):
    super().__init__(**kwargs)
    self.name = name
    self.age = age

  def display_person(self):
    print("Name:", self.name)
    print("Age:", self.age)

class Teacher(Person):
  def __init__(self, name, age ,subject, **kwargs):
    super().__init__(name=name, age=age, **kwargs)
    self.subject = subject

  def display_teacher(self):
    print("Subject:", self.subject)

class Student(Person):
  def __init__(self,name, age, student_id, **kwargs):
    super().__init__(name=name, age=age, **kwargs)
    self.student_id = student_id

  def display_student(self):
    self.display_person()
    print("Student ID:", self.student_id)

class TeachingAssistant(Student, Teacher):
  def __init__(self,name, age, student_id, subject, department, salary):
    super().__init__(name=name, age=age, student_id=student_id, subject=subject)
    self.department = department
    self.salary = salary


  def display_ta(self):
    print("Department:", self.department)
    print("Salary:", self.salary)

ta = TeachingAssistant("shradha", 22, "s101", "python", "computer science", 50000)

ta.display_person()
ta.display_teacher()
ta.display_student()
ta.display_ta()

class OTTPsubscription:
  def __init__(self, subscription_id, plan, total_payment):
    self.id = subscription_id
    self.plan = plan
    self.total_payment = total_payment

  def subscription(self):
    print(f"Subscriber with {self.id} id subscribed to the {self.plan} ")

  def unsubscribe(self):
    print(f"Subscriber with {self.id} unsubscribed to {self.plan}")

class PremiumSubscription(OTTPsubscription):
  def __init__(self, subscription_id, plan, total_payment, screens):
    super().__init__(subscription_id, plan, total_payment)
    self.max_screens = screens

  def set_max_screen(self):
    print(f"Maximum screen set to {self.max_screens} in the premium plan")

obj = PremiumSubscription(1222,"Pro", 80000, 7)

obj.set_max_screen()

obj.subscription()

obj.unsubscribe()

