# -*- coding: utf-8 -*-
"""day14-dsml - lambda,list,dict.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bc1MorsEK88UN42e_L1pzwoQVvX6L0VW
"""

data = lambda a,b: a+b

data(3,4)

#square using lambda function
square = lambda x:x*x

square(6)

#map (function, iterable)
lst = [1,2,3,4,5,6,7,8,9]
evens = list(filter(lambda x:x%2 == 0, lst))
evens

# sort a list of tuples using lambda function
students = [
    ("Ram", 80),
    ("Hari", 95),
    ("Sita", 90),
    ("Gita", 85)
]

students.sort(key = lambda x:x[1])
students

#using reduce(): sum of all numbers -> lambda
from functools import reduce

numbers = [10, 20, 30, 40, 50]

total = reduce(lambda x, y: x + y, numbers)

print("Sum =", total)

from functools import reduce

numbers = [1,2,3,4,5]
result = reduce(lambda a,b: a+b, numbers)
result

employees =[
    {"name": "Ram", "salary": 30000},
    {"name": "Hari", "salary": 40000},
    {"name": "Sita", "salary": 50000}

]

employees.sort(key = lambda emp:emp["salary"])
employees

data1 = ["welcome", "to", "dsml", "class"]
for word in data1:
  if "e" in word:
    print(word.upper())

#list comprehension
[word.upper() for word in data1 if "e" in word]

#odd even using list comprehension
numbers = [1,2,3,4,5,6]

["even" if num % 2 == 0 else "odd" for num in numbers]

numbers = [1,2,3,4,5,6]
evens = [num for num in numbers if num%2 ==0]
print(evens)

list1 = [1,2]
list2 = ["A", "B"]

pairs = [(x,y) for x in list1 for y in list2]
print(pairs)

{num : num*num for num in range(1,11)}

numbers = [1,2,3,4,5,6]
{num: num**2 for num in numbers if num%2==0}

original_dict = {"ram":39, "sita":48, "gita":57, "lina":90}
even_dict = {k:v for (k,v) in original_dict.items() if v%2==0}
even_dict

original_dict = {"ram":39, "sita":48, "gita":57, "lina":90}
even_dict = {k:v for (k,v) in original_dict.items() if v%2==0 if v>=40}
even_dict

"""**practise question**

"""

#using list comprehension convert a list of names into uppercase
lst = ["sita", "ram", "lina", "gita"]
[name.upper() for name in lst]

#create dict using dict comprehension where each word in a list is a key and its length is the value
dict1 = {"apple":5, "banana":6, "kiwi": 4, "pear": 4}
{k:v for (k,v) in dict1.items()}

#use lambda function with filter() to extract all odd numbers from a list
lst = [1,2,3,4,5,6,7,8,9]
odd = list(filter(lambda x:x%2 != 0, lst))
odd

#use lambda function with map() to add 10 to every elements in a list
num = [2,3,4,5,6,7]
final = list(map(lambda x:x+10 , num))
final

"""given a list of student names, use list comprehension to select names with more than 4 characters and dictionary comprehension to store each selected names with its character count"""

names = ["Sita", "Alice", "Megha", "Ram", "Alex", "Frank"]
selected_names = [name for name in names if len(name) > 4]
char_count = {name: len(name) for name in selected_names}
print(char_count)

