# -*- coding: utf-8 -*-
"""day13_dsml_lambda.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EHi6V4q7TJS3E05YTlagAt5NMIDZa5yt
"""

data =[1,2,3,4,5]
for i in range(len(data)):
  print(i)

def sum(*args):
  total =0
  for num in args:
    total += num
  return total

sum(1,3)

def add(*args):
  return max(args)

print(add(1,2,4))

def func(**kwargs):
  for k, val in kwargs.items():
    print(k, "=", val)

func(s1='python', s2='is', s3='awesome')

def introduce(**kwargs):
  details=[]
  for k,v in kwargs.items():
    details.append(k + ":" + str(v))
  return",".join(details)

introduce(name ="alice", age="25", city="nyc")

#subject and student details

def student_info(*args, **kwargs):
  print("subject:", args)
  print("details:", kwargs)

student_info("math", "science", "physics", name="shradha", course="skillsikshya")

"""Q . write a function that accepts products and their prices as keyword arguments and returns the total


"""

def product_info(**kwargs):
    total = 0
    for price in kwargs.values():
        total += price
    return total

result = product_info(laptop=500000, mouse=7500, speaker=8000)
print("Total:", result)