# -*- coding: utf-8 -*-
"""day38_dsml_revision.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FEYo1ILyVRTEol6tj9abVMfspC7GftDq
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

survey_df = pd.read_csv("/content/drive/MyDrive/dsml/survey_student.csv")

survey_df

survey_df.columns = [
    "Timestamp",
    "Sex",
    "Matric_GPA",
    "Year_2023",
    "Faculty",
    "Academic_GPA_2023",
    "Accommodation",
    "Monthly_Allowance",
    "Scholarship",
    "Study_Hours",
    "Socialising_Frequency",
    "Alcohol_Drinks",
    "Missed_Classes",
    "Failed_Modules",
    "Relationship",
    "Parents_Approve_Alcohol",
    "Parent_Relationship"
]

survey_df

survey_df = survey_df.drop(columns = ["Timestamp"])

survey_df

survey_df = survey_df.drop(columns = ["Relationship"])
survey_df

#addressing null values
survey_df.isnull().sum()

survey_df["Matric_GPA"] = (
    survey_df["Matric_GPA"]
    .fillna(survey_df["Matric_GPA"].median())
)

survey_df.isnull().sum()

survey_df["Sex"] = survey_df["Sex"].fillna(survey_df["Sex"].mode()[0])

survey_df.isnull().sum()

survey_df["Year_2023"] = survey_df[
    "Year_2023"
].fillna(
    survey_df["Year_2023"].mode()[0]
)

survey_df["Scholarship"] = (
    survey_df["Scholarship"]
    .fillna(survey_df["Scholarship"].mode())
)

survey_df["Faculty"] = survey_df[
    "Faculty"
].fillna(
    survey_df["Faculty"].mode()[0]
)

survey_df["Academic_GPA_2023"] = survey_df[
    "Academic_GPA_2023"
].fillna(
    survey_df["Academic_GPA_2023"].median()
)

survey_df["Accommodation"] = survey_df[
    "Accommodation"
].fillna(
    survey_df["Accommodation"].mode()[0]
)

survey_df.isnull().sum()

survey_df["Monthly_Allowance"] = survey_df[
    "Monthly_Allowance"
].fillna(
    survey_df["Monthly_Allowance"].mode()[0]
)

survey_df["Study_Hours"] = survey_df[
    "Study_Hours"
].fillna(
    survey_df["Study_Hours"].mode()[0]
)

survey_df["Socialising_Frequency"] = survey_df[
    "Socialising_Frequency"
].fillna(
    survey_df["Socialising_Frequency"].mode()[0]
)

survey_df["Alcohol_Drinks"] = survey_df[
    "Alcohol_Drinks"
].fillna(
    survey_df["Alcohol_Drinks"].mode()[0]
)

survey_df["Missed_Classes"] = survey_df[
    "Missed_Classes"
].fillna(
    survey_df["Missed_Classes"].mode()[0]
)

survey_df["Failed_Modules"] = survey_df[
    "Failed_Modules"
].fillna(
    survey_df["Failed_Modules"].mode()[0]
)

survey_df["Parents_Approve_Alcohol"] = survey_df[
    "Parents_Approve_Alcohol"
].fillna(
    survey_df["Parents_Approve_Alcohol"].mode()[0]
)

survey_df["Parent_Relationship"] = survey_df[
    "Parent_Relationship"
].fillna(
    survey_df["Parent_Relationship"].mode()[0]
)

survey_df.isnull().sum()

survey_df["Scholarship"] = survey_df[
    "Scholarship"
].fillna(
    survey_df["Scholarship"].mode()[0]
)

survey_df.isnull().sum()

#outlier handling
survey_df.plot.box(column = "Matric_GPA")

Q1 = survey_df["Matric_GPA"].quantile(0.25)
Q3 = survey_df["Matric_GPA"].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

print("Lower bound:", lower)
print("Upper bound:", upper)

outliers = survey_df[
    (survey_df["Matric_GPA"] < lower) |
    (survey_df["Matric_GPA"] > upper)
]

outliers

survey_df["Matric_GPA"] = survey_df[
    "Matric_GPA"
].clip(lower=lower, upper=upper)

survey_df.head()

#feature enggineering
import pandas as pd

survey_df["GPA_category"]= pd.cut(
    survey_df["Matric_GPA"],
    bins = [0, 50, 70, 100],
    labels = ["Below average", "Average", "High"]
)

survey_df.head()

#encoding
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

survey_df["Scholarship_Encoded"] = encoder.fit_transform(
    survey_df["Scholarship"]
)

survey_df.head()

#normalization

from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

survey_df["GPA_Normalized"] = scaler.fit_transform(
    survey_df[["Matric_GPA"]]
)

survey_df.head()

#EDA

import matplotlib.pyplot as plt

survey_df["Scholarship"].value_counts().plot(
    kind="pie",
    autopct="%1.1f%%",
    figsize=(7, 7)
)

plt.title("Students on Scholarship/Bursary")
plt.show()

survey_df["Sex"].value_counts().plot(
    kind="bar",
    figsize=(8, 5),
    xlabel = "Sex",
    ylabel = "numeber of students",
    grid =True,
    color = "blue"
)
plt.title("Bar chart to show No. of male and female students")
plt.show()

#boxplot
survey_df["Matric_GPA"].plot(
    kind="box",
    figsize=(6, 5),
    ylabel = "GPA %"
)

plt.title("Matric GPA Box Plot")
plt.show()

#sactterplot
survey_df.plot(
    kind="scatter",
    x="Study_Hours",
    y="Academic_GPA_2023",
    figsize=(8, 5),
    xlabel= "Study Hours",
    ylabel = "GPA"
)

plt.title("Study hours vs GPA")
plt.show()

#line graph

survey_df[["Matric_GPA", "Academic_GPA_2023"]].loc[:200].plot(
    kind="line",
    figsize=(10, 5),
    color=["blue", "orange"]
)
plt.show()

#heatmap
import seaborn as sns

correlation = survey_df.corr(numeric_only=True)
correlation

sns.heatmap(correlation , annot = True, cmap = "jet")

