# -*- coding: utf-8 -*-
"""day10_dsml_function.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D_m7WSkHr_kLLKfJtkxbGjXI4_RnLD-E

Function
"""

def sum(a,b):
  return a+b

sum(4,5)

def sum(a,b):
  result = a+b
  return result

print(sum(5,6))

"""types of function
1. no parameter , no return type
2. has parameter, no return type
3. no parameter , has return type
4. has parameter , has return type
"""

#1
def greet():
  print("Hello! welcome to skillshikshya")

#function call
greet()

#2 no parameter, has return type

def get_pi():
  pi = 3.14
  return pi

value = get_pi()
print("value of pi:" , value)

#3 has parameter , no return type
def greet(name):
  print("Hello , {name}!")

greet("Shradha")

#4 has parameter , has return type

def add(a,b):
  sum = a+b
  return sum

#function call
result = add(10,20)
print("sum is:" , result)

"""class task

write a function area (length, breadth) that returns the area of rectangle

"""

def rect(l,b):
  area = l*b
  return area


result = rect(2,5)
print("area is:", result)

"""write a python program using user defined function that:
- takes two numbers from user
- takes an operator sign (+ , -, * , /)
- performs the selected operation
- displays the result


"""

num1 = int(input("enter first number:"))
num2 = int(input("enter second number:"))
operator = input("enter operator (+, -, *, /):")

def calculator(num1, num2, operator):
  if operator == '+':
    return num1 + num2
  elif operator == '-':
    return num1 - num2
  elif operator == '*':
    return num1 * num2
  elif operator == '/':
    return num1 / num2
  else:
    return "invalid operator"

result = calculator(num1, num2, operator)
print(result)

"""write user defined function that takes 5 user inputs

if user enters integer, add it to a list

if user enters float , remove the last element

finally dispaly the updated list after each operation
"""

num = "2.5"

if "." in num:
  print("yes")
else:
  print("no")

def lst_operation():
  number = []
  for i in range(5):
    value = input(f"enter value {i+1}:")
    if "." in value:
      if len(number) > 0:
        removed = number.pop()
        print(f"float detected. removed: {removed}")
      else:
        print("float detected, but the list is empty")

    else:
      number.append(int(value))
      print(f"integer {value} added to the list")
    print("updated list:", number)

lst_operation()

