# -*- coding: utf-8 -*-
"""dsml_day7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15fmtFlvjoQ0qhvmFbF518hoNflOMgLVK
"""

dict1={
    "name":"shradha",
    "phone": 2929922,
    "address":"sitapaila"
}

dict1

dict1["name"]

del dict

person = dict([("name", "shradha"), ("address", "ktm")])
print(person)

dict_data = {
    "name":"shradha",
    "phone": 2929922,
    "address":"sitapaila"
}

dict_data

dict_data["phone"]=9841260034

dict_data

dict_data.keys()

dict_data.values()

dict_data.values()

dict_data.pop("name")

dict_data

dict_data.popitem()

dict_data

#difference between pop in list or tuple and pop in dictionary?

lst=[1,2,3,4,5]
lst.pop()

dict_ ={
    "name":"shradha",
    "phone": 2929922,
    "address":"sitapaila"
}
dict_.pop("name")

del dict_["phone"]

dict_

dict1={
    "name":"ram",
    "address":"Ktm",
    "age": 20
}
dict1

dict2={
    "phone": 23455,
    "skill":"dsml"
}
dict2

dict1.update(dict2)
dict1

dict2.update(dict1)
dict2

dict3={
    "gender":"male",
    "hobby":"painting"
}
dict3

student_dict = {**dict1, **dict2, **dict3}
student_dict

student = {"b":2, "a":1, "c":2}
result = sorted(student)
result

dict1 | dict2

max(student_dict)

min(student_dict)

dict_={
    "a":30,
    "b":35,
    "c":20
}
print(max(dict_.values()))
print(min(dict_.values()))

student_det ={
    "name":"hari",
    "age":"20",
    "faculty": "cs"
}
student_det

student_det["phone"] = 90448848

student_det

student_det["age"]=24
student_det

student_det["city"]= "ktm"

del student_det["city"]

student_det

