# -*- coding: utf-8 -*-
"""day22_dsml_magicmethods_filehandling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1URnAiTUq_kuibZg8y_9q-PybYLFh826g

Magic methods, file handling, modules and packages
"""

#magic method

class BankCustomer:
  def __init__(self,name,age):
    self.name = name
    self.age = age

  #called by print
  def __str__(self):
    return f"{self.name} is {self.age} years old"


#called by repr
  def __repr__(self):
    return f"{self.name} is {self.age} years old"

  #called by len
  def __len__(self):
    return self.age

#makes object callable like a fuction
  def __call__(self, gender = "Male"):
    print(f"{self.name} is {self.age} years old and {gender}")

customer = BankCustomer("John",30)

print(customer)

print(repr(customer))

print(len(customer))

print(customer())

print(customer("Female"))

with open('dummy.txt', 'w') as f:
  f.write('This is a dummy file created by the agent.')
print('dummy.txt created successfully.')

with open('dummy.txt', 'a') as f:
  f.write('hello i am')
print('dummy.txt created successfully.')

"""This code creates a file named `dummy.txt` in the current working directory and writes a line of text into it. The `with` statement ensures the file is properly closed after writing."""

import json

with open('database.json', 'w') as f:
  json.dump({"name": "Shradha", "class": "DSML-12"}, f)
print("file created")

import os
os.remove('dummy.txt')
print('dummy.txt removed successfully.')

