# -*- coding: utf-8 -*-
"""day17_dsml_oop.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fsHxt_1jX8ozRUkYtKOxrFKQg3z04WGA
"""

#class diagram
#   - attributes
#   - methods

class Vehicles:
  def bus(self, name): # methods
    print("this is the section:", name)
  def truck(self):
    print("hello i am truck")

obj1 = Vehicles() #object call
obj1. bus("driver")

obj1.truck()

class Fruits:
  def apple(self):
    print("red color")
  def banana(self):
    print("yellow color")

obj = Fruits()

obj.apple()

obj.banana()

class Fruit:
  def __init__(self, shape, color, taste):
    self.shape = shape
    self.color = color
    self.test = taste

obj1 = Fruit("round", "red", "yummy")
obj1.color

class Product:
  tax_rate = 0.13 #class atrribute

  def __init__(self, name, price):
    self.name = name
    self.price = price

p1 = Product("Laptop", 5000)
p1.tax_rate

p2 = Product("Phone", 20000)
p2.tax_rate

class Calculator:
  #a utility function that logically belong to the class but doesnt need self or cls
  @staticmethod
  def add(a,b):
    return a+b

Calculator.add(2,3)

class EmailValidator:
  @staticmethod
  def _is_valid(email):
    return "@" in email

EmailValidator._is_valid("test@gmail.com")

class Student:
  school = "skillshikshya"
  @classmethod
  def get_school(cls):
    print(cls.school)

Student.get_school()

"""class task"""

class Calculator:
  #class attribute
  company = "ABC Calculator"

  def __init__(self):
    self.num1 = float(input("Enter first num:"))
    self.num2 = float(input("Enter second num:"))
    self.operator = input("Enter operator (+, -, *, /)")

  #instance method
  def Calculator(self):
    if self.operator == "+":
      print("result:", self.num1 + self.num2)
    elif self.operator == "-":
      print("result:", self.num1 - self.num2)
    elif self.operator == "*":
      print("result:", self.num1 * self.num2)
    elif self.operator == "/":
      if self.num2 != 0:
        print("result:", self.num1 / self.num2)
      else:
        print("Cannot be divided by 0")
    else:
      print("invalid")


  #class method
  @classmethod
  def show_company(cls):
    print("Company name:", cls.company)



  #static method
  @staticmethod
  def welcome():
    print("Welcome to calculator program")


obj=Calculator()
Calculator.welcome()
Calculator.show_company()
obj.calculate()

