# -*- coding: utf-8 -*-
"""day31_dsml_matplotlib.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CIY88HdxqNVKB1soXWv2WgbAwOYnoZTg
"""

import pandas as pd

titanic_df = pd.read_csv('/content/drive/MyDrive/dsml/titanic.csv')

#how many sex = female and survived numbers in dataset

titanic_df.value_counts(["Sex", "Survived"], ascending = True)

titanic_df[titanic_df["Sex"]=="female"].value_counts("Survived", ascending = True)

titanic_df[(titanic_df["Embarked"]== "S") & (titanic_df["Sex"]=="male")]["Survived"].value_counts()

import numpy as np
fare_bins = [0,50,100,300,512]
fare_labels = ["Low Fare", "medium", "high", "very high"]

titanic_df["FareGroup"] = pd.cut(
    titanic_df["Fare"],
    bins = fare_bins,
    labels = fare_labels,
    include_lowest = True
)

titanic_df

import matplotlib.pyplot as plt

titanic_df["Sex"].value_counts().plot.bar()
plt.title("Gender Distribution")
plt.show()

titanic_df["Survived"].value_counts().plot(
    kind = "bar",
    title = "Count of survived passengers",
    figsize=(5,5),
    legend = True,
    yticks = list(range(0,600,50)),
    xlabel= "Survived",
    ylabel = "Count",
    grid = True,
    color = "red"
)

pd.crosstab(titanic_df.Survived, titanic_df.Sex).plot(
    kind = "bar",
    title = "Count of survived passengers",
    figsize = (5,5),
    legend = True,
    xlabel= "Survived (0=No, 1=Yes)",
    ylabel= "No. of passengers",
    grid = True,
    colormap = "Dark2"
)

df = pd.read_csv("/content/drive/MyDrive/dsml/titanic.csv")
df.set_index("Age", inplace=True)

# 3. Plot the pie chart from the numerical column
df["Embarked"].value_counts().plot.pie(
    autopct="%1.1f%%", startangle=90, figsize=(6, 6)
)

# 4. Customize and display
plt.title("My Pie Chart")
plt.ylabel("")  # Hides the default vertical column label
plt.show()

age_count = df.reset_index().groupby("Embarked")["Age"].count()

# Create pie chart
plt.pie(
    age_count,
    labels=age_count.index,
    autopct="%1.1f%%"
)

plt.title("Age Count by Embarked")
plt.show()

pd.crosstab(titanic_df.Survived, titanic_df.Sex).plot(
    kind = "pie",
    subplots = True,
    figsize = (10,15),
    colormap = "Dark2"
)
plt.show()

pd.crosstab(titanic_df.Survived, titanic_df.Sex).plot(
    kind = "pie",
    subplots = True,
    figsize = (10,15),
    autopct="%1.1f%%",
    colormap = "Dark2"
)
plt.show()

#line graph
titanic_df["Age"].loc[:100].plot.line(figsize = (10,5))

titanic_df[["Age", "Fare"]].loc[:200].plot(
    kind="line",
    figsize=(10, 5),
    color=["blue", "orange"]
)

titanic_df.loc[:200][["Fare", "Age"]].plot.line(figsize = (10,5))

