# -*- coding: utf-8 -*-
"""day29_dsml_svd, eigen, pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CKdhqsSHbgG-Abj_BkOXtMepFIdA0AZO
"""

import numpy as np

A = np.array([
    [1,2],
    [3,4]
])
eigenvalues , eigenvectors = np.linalg.eig(A)

print(eigenvalues)

print(eigenvectors)

#Singular value decomposition

U , S, V = np.linalg.svd(A)
print("U matrix: \n ", U)
print("signma values:", S)
print("V matrix: \n", V)

print(U @ U.T) #identity matrix

import pandas as pd

a = ['g', 'e','f', 's']
res = pd.Series(a)
print(res)

a={
    "id": 101,
    "name":"shradha",
    "state":"ktm",
    "country": "nepal"
}
res = pd.Series(a)
print(res)

res.ndim

#dataframe: combination of rows and columns

res_data = pd.DataFrame(res, columns =['data1'])
res_data

res_data.ndim

res_data['data1'].isnull().sum()

a ={
    "name": ["Defoe", "J. Terry", "Lampard"],
    "Team": ["NewCastle", "Chelsea", "Chelsea"],
    "Number": [23, 5, 22],
    "Age": [33, 38, None]
}
df = pd.DataFrame(a)
df

df[["Team", "Age"]]

df[["Team", "Age", "name"]]

print(df["Age"].isna().sum())

df["Age"].isna()

res = df.loc[df["name"]=="Defoe"]
res

#hw - difference between the loc and iloc?

#dataframe save to csv file
df.to_csv("data.csv", index=False)

data = pd.read_csv("data.csv" )

data

print(df["name"])

print(df["Age"])

print(df["Number"])

