# -*- coding: utf-8 -*-
"""day23_dsml.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qgjz6TfBVcJF-D_oye_61qKRVoNVkXjy

Python property decorator, regular expression
"""

#getter (@property)

class Student:
  def __init__(self, name, age , grade):
    self.name = name
    self.age = age
    self._grade = grade

  @property
  def get_grade(self):
    return self._grade

  @get_grade.setter
  def set_grade(self, value):
    if not isinstance(value, int):
      raise TypeError("Grade must be an integer")
    if value < 0 or value > 100:
      raise ValueError("Grade must be between 0 and 100")
    self._grade = value

obj = Student("Shradha", 22, 90)

obj.get_grade

#setter (@age.setter)
# a setter is called when you assign a value

obj.set_grade = 20

obj.get_grade

#regex
import re

import re
import requests
from bs4 import BeautifulSoup #install bs4


def scrape_and_clean(url: str) -> str:
    """
    Scrape webpage and return cleaned text.
    """

    # Request webpage
    headers = {
        "User-Agent": (
            "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
            "AppleWebKit/537.36 (KHTML, like Gecko) "
            "Chrome/137.0.0.0 Safari/537.36"
        )
    }

    response = requests.get(url, headers=headers, timeout=20)
    # print(requests.get(url, headers=headers, timeout=20))
    response.raise_for_status()

    # Parse HTML
    soup = BeautifulSoup(response.text, "html.parser")

    # Remove unwanted tags
    for tag in soup([
        "script",
        "style",
        "noscript",
        "header",
        "footer",
        "nav",
        "iframe",
        "svg",
        "img"
    ]):
        tag.decompose()

    # Extract text
    text = soup.get_text(separator=" ")
    # print(text)
    # ---------------------
    # REGEX CLEANING
    # ---------------------

    # Remove URLs
    text = re.sub(r'https?://\S+|www\.\S+', ' ', text)

    # Remove email addresses abc@gmail.com
    text = re.sub(
        r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b',
        ' ',
        text
    )

    # Remove phone numbers
    text = re.sub(
        r'\+?\d[\d\s\-\(\)]{7,}\d',
        ' ',
        text
    )

    # Remove non-alphanumeric characters
    text = re.sub(r'[^a-zA-Z0-9\s]', ' ', text)

    # Remove standalone numbers (optional)
    text = re.sub(r'\b\d+\b', ' ', text)

    # Collapse multiple spaces
    text = re.sub(r'\s+', ' ', text)

    # Strip leading/trailing spaces
    text = text.strip()

    return text


if __name__ == "__main__":
    url = "https://kathmandupost.com/national/2026/08/05/two-sarlahi-farmers-jailed-in-bihar-over-fertiliser-transport-granted-bail%22"

    cleaned_text = scrape_and_clean(url)

    print(cleaned_text[:])  # preview first 5000 chars

import csv
import re
import requests
from bs4 import BeautifulSoup

def scrape_and_clean(url: str) -> str:
    headers = {
        "User-Agent": (
            "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
            "AppleWebKit/537.36 (KHTML, like Gecko) "
            "Chrome/137.0.0.0 Safari/537.36"
        )
    }

    response = requests.get(url, headers=headers, timeout=20)
    response.raise_for_status()

    soup = BeautifulSoup(response.text, "html.parser")

    for tag in soup([
        "script", "style", "noscript", "header",
        "footer", "nav", "iframe", "svg", "img"
    ]):
        tag.decompose()

    text = soup.get_text(separator=" ")

    # Clean text
    text = re.sub(r'https?://\S+|www\.\S+', ' ', text)
    text = re.sub(r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}\b', ' ', text)
    text = re.sub(r'\+?\d[\d\s\-\(\)]{7,}\d', ' ', text)
    text = re.sub(r'[^a-zA-Z0-9\s]', ' ', text)
    text = re.sub(r'\b\d+\b', ' ', text)
    text = re.sub(r'\s+', ' ', text).strip()

    return text

# Main program
url = "https://kathmandupost.com/national/2026/08/05/two-sarlahi-farmers-jailed-in-bihar-over-fertiliser-transport-granted-bail"

cleaned_text = scrape_and_clean(url)

# Save to CSV
with open("news_data.csv", "w", newline="", encoding="utf-8") as file:
    writer = csv.writer(file)
    writer.writerow(["URL", "Cleaned Text"])   # Header
    writer.writerow([url, cleaned_text])

print("Data saved to news_data.csv")

"""Web scraping"""

import re
import csv
import requests
from bs4 import BeautifulSoup

headers = {
    "User-Agent": (
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/137.0.0.0 Safari/537.36"
    )
}


def clean_text(text):
    text = re.sub(r'https?://\S+|www\.\S+', ' ', text)
    text = re.sub(r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}\b', ' ', text)
    text = re.sub(r'\+?\d[\d\s\-\(\)]{7,}\d', ' ', text)
    text = re.sub(r'[^a-zA-Z0-9\s]', ' ', text)
    text = re.sub(r'\b\d+\b', ' ', text)
    text = re.sub(r'\s+', ' ', text).strip()
    return text


def scrape_article(url):
    try:
        response = requests.get(url, headers=headers, timeout=20)
        response.raise_for_status()

        soup = BeautifulSoup(response.text, "html.parser")

        # Title
        title = ""
        if soup.title:
            title = soup.title.get_text(strip=True)

        # Description
        description = ""
        desc = soup.find("meta", attrs={"name": "description"})
        if desc:
            description = desc.get("content", "")

        # Remove unwanted tags
        for tag in soup([
            "script", "style", "noscript",
            "header", "footer", "nav",
            "iframe", "svg", "img"
        ]):
            tag.decompose()

        article_text = clean_text(soup.get_text(separator=" "))

        return {
            "Title": title,
            "Description": description,
            "URL": url,
            "Content": article_text
        }

    except Exception as e:
        print("Error:", url)
        print(e)
        return None


def get_links(homepage):
    response = requests.get(homepage, headers=headers)
    soup = BeautifulSoup(response.text, "html.parser")

    links = set()

    for a in soup.find_all("a", href=True):
        href = a["href"]

        if href.startswith("/"):
            href = homepage.rstrip("/") + href

        if href.startswith("https://kathmandupost.com/"):
            links.add(href)

    return list(links)


homepage = "https://kathmandupost.com"

links = get_links(homepage)

print("Found:", len(links), "links")

# Maximum 200 links
links = links[:200]

with open("kathmandu_post_news.csv", "w", newline="", encoding="utf-8") as file:
    writer = csv.DictWriter(
        file,
        fieldnames=["Title", "Description", "URL", "Content"]
    )

    writer.writeheader()

    for i, link in enumerate(links, start=1):
        print(f"{i}. Scraping {link}")

        data = scrape_article(link)

        if data:
            writer.writerow(data)

print("Finished! CSV saved as kathmandu_post_news.csv")

