# -*- coding: utf-8 -*-
"""day24_dsml_revision.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dmoopJB5BIzdODrPljfhvTd4wI1HgN_q
"""

dict = {
    "name" : "SHradha",
    "rollnum": 20
}

dict

dict.values()

dict.get("name")

#practise question

employee = {
    "Hari": 25000,
    "Sita": 30000,
    "Gita": 35000,
    "Ram": 80000,
    "Ganesh": 60000
}

name = input("Enter a name:")
if name in employee:
  print("Salary:", employee[name])
else:
  print("Employee not found")

#student record
student = {
    "Name": "Shradha",
    "Age": 20,
    "Grade": "A"
}

for key, value in student.items():
    print(key, ":", value)

#student marks analyzer

marks = {
    "Rita": 50,
    "Sita": 70,
    "Gita": 80

}

highest = max(marks, key=marks.get)
print("Highest Marks:")
print(highest, "-", marks[highest])

# Student with lowest marks
lowest = min(marks, key=marks.get)
print("\nLowest Marks:")
print(lowest, "-", marks[lowest])

# Average marks
average = sum(marks.values()) / len(marks)

print("\nAverage Marks:", average)

"""recursion

Recursion is a programming technique where a function calls itself,until a stopping condition


1. base case - stopping condition
2. recursive case



factorial
5! = 5*4*3*2*1

"""

def condition(n):
  if n==0 or n ==1: #base case
    return 1
  return n*condition(n-1) #recursive case

condition(5)

#fibonnaci
def fibonnaci(n):
  if n<=1:
    return n
  return fibonnaci(n-1)+fibonnaci(n-2)


terms = 9
for i in range(terms):
  print(fibonnaci(i), end = " ,")

#decorator

def decorator(func):
  def wrapper():
    print("Before")
    func()
    print("After")
  return wrapper

@decorator
def hello():
  print("Hello world")

hello(

)

"""write a decorator login_required that checks whether a user is logged in. if the variable logged_in is True, execute the function, otherwise print "Access denied"
"""

def login_required(func):

    def wrapper():
        logged_in = True

        if logged_in:
            func()
        else:
            print("Access denied")

    return wrapper

@login_required
def dashboard():
    print("Welcome to dashboard")

dashboard()

class Dsml:
  def show(self,*args, **kwargs):
    print(args)
    print(kwargs)

obj = Dsml()
obj.show(20,[1,2,3,4,5], a=20)

