# -*- coding: utf-8 -*-
"""day15_recursion, decorators.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w_kZopkZeZA726ftLTnIyIMua5ENCPRp
"""

#factorial number
#1 n*(n-1) (recursive case)
#2 1 or 0 (base case)

def factorial(n):
  if n==0 or n==1:
    return 1
  else:
    return n*factorial(n-1)

factorial(5)

#write a recursive python function fibonacci(n) that returns the nth fibonacci number

def fibonacci(n):
    if n <= 1:
        return n
    return fibonacci(n - 1) + fibonacci(n - 2)

for i in range(10):
  print(fibonacci(i), end = ",")

def fibo(n):
  if n<=1:
    return n
  else:
    return(fibo(n-1)+ fibo(n-2))

#by user input

nterms = int(input("Enter a number:"))
if nterms <=0:
  print("Please enter a positive integer")
else:
  print("Fibonacci sequence:")
  for i in range(nterms):
    print(fibo(i))

"""Decorator in python"""

#nested loop
  def outer(x):
    def inner(y):
      return x+y
    return inner

add_five = outer(5)

add_five

result = add_five(6)
result

#pass function as argument
def add(x,y):
  return x+y

def calculate(func, x, y):
  return func(x,y)

result = calculate(add, 4, 5)
result

#return a function as value
def greeting(name):
  def hello():
    return f"Hello {name}!"
  return hello

greet = greeting("Shradha")

greet

greet()

def myWrapper(func):
  def myInnerFunc():
    print("Inner wrapper")
    func()
  return myInnerFunc

@myWrapper
def myFunc():
  print("Hello, world!")

myFunc()

def logger(func):
  def wrapper(*args, **kwargs):
    print(f"calling {func.__name__}")
    return func(*args, **kwargs)
  return wrapper

@logger
def greet(name,age):
  print(f"Hello {name}, Age: {age}")

greet("Shradha", age = 21)

