# -*- coding: utf-8 -*-
"""day8_dsml.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ctlbVt97J62Esac2OVGWcT-J81u3D9DR

conditional statement
"""

number = 10
if(number >20):
  print("here")
else:
  print("there")

age = 10
if age<=12:
  print("travel for free")
else:
  print("pay for ticket")

age = 25
if age<=12:
  print("child")
elif age<=19:
  print("teenager")
elif age<=35:
  print("young adult")
else:
  print("adult")

#voting machine
age = int(input("Enter age to check voting:"))
if age>=18:
  citizenship = input("DO you have a citizenship? (yes/no)")
  if citizenship.lower() == "yes":
    print("You are eligible to vote")
  else:
    print("You are not eligible to vote")
else:
  print("You are not eligible to vote")

#task
age = int(input("Enter your age:"))
if age>=60:
  membership = input("Do you have membership (yes/no)?")
  if membership.lower() == "yes":
    print("eligible for 30% discount")
  else:
    print("eligible for 20% dicount")
else:
  print("Not eligible for senior discount")

#using boolean

age = 70
is_member = False
if age>=60:
  if is_member:
    print("eligible for 30% discount")
  else:
    print("eligible for 20% discount")
else:
  print("Not eligible for senior discount")

# value_if_true if condition else value_if_false
#ternary operator

n = int(input("enter a number:"))
print("even" if(n%2 == 0)else "odd")

#class task - see grading system
marks = int(input("Enter your marks: "))

if marks>=90 and marks<=100:
  print("Grade A+")
elif marks>=80 and marks<=89:
  print("Grade A")
elif marks>=70 and marks<=79:
  print("Grade B+")
elif marks>=60 and marks<=69:
  print("Grade B")
elif marks>=50 and marks<=59:
  print("Grade C+")
elif marks>=40 and marks<=49:
  print("Grade C")
elif marks>=30 and marks<=39:
  print("Grade D")
else:
  print("NG")

# and operator

age = 20
citizenship = True

if age>=18 and citizenship:
  print("Eligible to vote")
else:
  print("Not eligible to vote")

#or operator
username = "admin"
password = "admin123"

if username == "admin1" or password == "admin1234":
  print("Login successful")
else:
  print("Invalid credentials")

# not operator
is_logged_in = False
if not is_logged_in:
  print("please login first")

#invalid email/password

email = 'admin@123'
password = 'admin123'

if email== "admin@123" and password == "admin123":
  print("Login successful")
else:
  print("Invalid credentials")

"""class tasks

"""

#class tasks
#a num is positive and even
num = 20
if num%2==0:
  print("Number is positive and even")
else:
  print("Number is not positive nor even")

#age is between 18 and 60 using and
age = int(input("enter a age:"))
if age>=18 and age<=60:
  print("age is between 18 and 60")
else:
  print("age is not between 10 and 60")

#if a day is saturday or sunday using or
day = "Saturday"
if day =="Saturday" or day =="Sunday":
  print("it is holiday")
else:
  print("it is not holiday")

#if a user is not logged in

is_logged_in = False
if not is_logged_in:
  print("please login first")
else:
  print("You are logged in")

##

