# -*- coding: utf-8 -*-
"""day16_error_handeling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FE5pUB3JMRYp1Ic7HZaXdSBXJJwCCI-I
"""

num = [1,2,3,4]
it = iter(num)

it

next(it)

#iterable
lst = [1,2,3]
for i in lst:
  print(i)

def count_up(n):
  i=1
  while i<=n:
    yield i
    i+=1

gent = count_up(3)

gent

print(next(gent))

print(next(gent))

print(next(gent))

"""iterators and generators are used to process large datasets efficiently without loading everything into memory. They are commonly used in data loading, batch generation, deep learning training pipelines, streaming data processing.

Error handling in python
"""

try:
  numerator = int(input("Enter a number to divide: "))
  denominator = int(input("Enter a number to divide by: "))
  result = numerator / denominator
except ZeroDivisionError:
  print("You can't divide by zero!")
except ValueError:
  print("Invalid input. Enter only numbers")
else:
  print(f"the result is {result}")
finally:
  print("execution complete")

#zero division error
num = 10
result = num/0
print(result)

#type error
a = 1
b = "shradha"
c = a+b
print(c)

len(100)

#value eror
num = int("abc")
print(num)

#index error
numbers = [10,20,30]
print(numbers[5])

#key error
student = {"name": "shradha", "age": 21}
print(student["address"])

#file not found
file = open("data.txt", "r")

try:
  file = open("sample.txt", "r")
  content = file.read()
except FileNotFoundError:
  print("error: file not found !")
else:
  print("file content ", content)
finally:
  print("file closed")

def set(age):
  if age < 0:
    raise ValueError("Age cannot be negative")
  else:
    print(f"Age set to {age}")

try:
  set(5)
except ValueError as e:
  print(e)

#custom exception

class InvalidAgeError(Exception):
  """"Custom expection for invalid age value"""
  pass

def set_age_custom(age):
  if age> 120:
    raise InvalidAgeError("age cannot be over 120")

set_age_custom(200)

