# -*- coding: utf-8 -*-
"""day32_dsml_visualization_in_pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_m_9r5FBnJclp_bnW8pBX769pur8YkAa
"""

import pandas as pd

titanic_df = pd.read_csv("/content/drive/MyDrive/dsml/titanic.csv")

titanic_df.shape

titanic_df.columns

"""Histograms are for continuous numerical data grouped into ranges( eg: ages 0-10, 11-20).

Bar charts are for categorical or discrete data( eg: comparing the sales of different types of fruits)

"""

titanic_df["Age"].plot.bar()

titanic_df["Age"].plot.hist()

titanic_df["Age"].plot.hist(bins=20, grid = True)

#bins = kati ota height ma utheko cha

#box plot - helpful to know outliers
titanic_df.plot.box(column= 'Age')

import seaborn as sns

correlation = titanic_df.corr(numeric_only=True)
correlation

sns.heatmap(correlation, annot = True, cmap= "jet")

#central tendency - mean, median, mode

import numpy as np
from scipy import stats
import matplotlib.pyplot as plt

x = np.random.standard_t(500, size = 1000)

x

x[:15]

_mean = np.mean(x)

print(f"Mean of x:{_mean}")

plt.hist(x, bins = 20, color="blue")

plt.axvline(x= _mean, color="red")

plt.hist(x, bins = 20 , color="blue")
plt.axvline(x= _mean, color="red")

#median

_median = np.median(x)

print(f"Median of x: {_median}")

plt.axvline(x= _median, color="red")

plt.hist(x, bins = 20 , color="red")
plt.axvline(x= _median, color="yellow")
plt.axvline(x= _mean, color="blue")

#mode

_mode =stats.mode(x).mode
print(f"Mode:{_mode}")

plt.hist(x, color="blue")
plt.axvline(_mode, color="red")
plt.show()

#topic research garni (10 days)
#problem domain, solution domain
#no kaggle dataset
#hcp dataset
#proposal - title, objective, methodology, result/conclusion (expected)

