# -*- coding: utf-8 -*-
"""day33_dsml_data Manipulation class.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TztrI5UmKxhH7Wcr3fxmPjZdcMynmX5i
"""

import pandas as pd

titanic_df = pd.read_csv("/content/drive/MyDrive/dsml/titanic.csv")

titanic_df.head()

#inserting and deleting columns and rows

titanic_df.drop([0,2,5], axis  = 0)

last_name = [name.split(",")[0] for name in titanic_df["Name"]]
titanic_df["last_name"] = last_name

titanic_df.head()

import random
id = [random.randint(1000,9999) for i in range(len(titanic_df))]
titanic_df["ID"] = id

titanic_df.head()

import pandas as pd

#adding row
titanic_df.loc[900] = [0,3,1,"Shradha", "female", 21.0, 1.0,0, "AS 324", 7.34, "C12", "C", "Shrestha" , 8000]

titanic_df.tail()

#null value or NAn

titanic_df.isna()

titanic_df.isna().sum()

#handling
# 1. remove null values
# 2. imputation (replacing null values with some values)

#remove null values
titanic_df_filter = titanic_df.dropna(subset = "Embarked", axis = 0, how = "all", ignore_index = True)

titanic_df_filter.isna().sum()

"""how = "any" -> remove the row if any checked value is Nan

how = "all" -> remove the row only if all the checked value are Nan
"""

titanic_df_filter.head()

titanic_df.Age.mean()

titanic_df.Age.plot.hist(bins = 20)

mean_age = titanic_df.Age.mean()

titanic_df.isna().sum()

titanic_df["Age"].fillna(mean_age, axis = 0, inplace = True)

titanic_df.isna().sum()

titanic_df.Age.plot.hist(bins = 20)

#imputation of age column w r t gender provided

titanic_df_2 = pd.read_csv("/content/drive/MyDrive/dsml/titanic.csv")

titanic_df_2.head()

mean_ages = titanic_df_2.groupby("Sex")["Age"].transform("mean")

titanic_df_2["Age"].fillna(mean_ages, inplace = True)

titanic_df_2.Age.plot.hist(bins = 20)

titanic_df_2.isna().sum()

import pandas as pd
#1 Create a sample dataFrame
df = pd.DataFrame({
    "Store": ["A", "A",  "B", "B", "B"],
    "Sales":[100,200,150,250,500]
})

#2 Calculate the group mean and assign it to a new column
df['Store_Mean_Sales'] = df.groupby('Store')["Sales"].transform('mean')

print(df)

titanic_df.Cabin

titanic_df.Cabin = titanic_df.Cabin.notna().astype(int)

titanic_df.Cabin

