# -*- coding: utf-8 -*-
"""day12_dsml.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QYSViNFE3JYyM_suX6mMBtzXL3BLDeWh

Map, filter , reduce , args and kwargs , doc string
"""

#enumertae()
#zip()

data1 = ["ram", "shyam", "gita", "rita"]
data2 = [20,30,40,50]

for i in zip(data1, data2):
  print(i)

for i, (name,age) in enumerate(zip(data1,data2)):
  print(i,name,age)

name=["ram", "sita", "gita"]
age=[20,30,27]
gender=["M", "F", "F"]
salary=[10000, 20000, 15000]

for n,a,g,s in zip(name , age, gender, salary):
  print(f"My name is", n, " age is", a, "gender is", g, "and salary is", s)

"""Map"""

#2 number multiply

def mux(a,b):
  return a+b

mux(3,4)

"""map (function , iterable) - used for list or tuple"""

def mux(x):
  return x*x

number = [1,2,3,4,5]
map_object = map(mux, number)

map_object

print(list(map_object))

"""class task


even number list

"""

def odd(num):
  return num%2 != 0

num = [1,3,5,6,8,10,12,13,14]
result = filter(odd, num)
print(__builtins__.list(result))

"""Filter (func, iterable)"""

#reduce()


from functools import reduce
mylist = [1,2,3,4,5]
def add(x,y):
  return x*y

red_obj = reduce(add, mylist)
red_obj

#class task
#find the maximum num using reduce function

nums = [4,9,2,8,1]
def max(x,y):
  if x>y:
    return x
  else:
    return y

final = reduce(max , nums)
print(final)

#doc string

def calculate_area(length , breadth):

  """"
  calculate the area of triangle:
  parameters:
  length(float): length of rectangle
  breadth(float): width of rectangle

  return:
  float: area of rectangle
  """

  return length*breadth

print(calculate_area.__doc__)

help(calculate_area)

def display(data):
  print(data)

display(["shradha", "shrestha"])

#solve using position argument

def area(*args):
  if len(args) ==2:
    l,w = args
    print("2D area =" , l*w)
  elif len(args) ==3:
    l,w,h = args
    print("3D volume=" , l*w*h)
  else:
    print("invalid")

area(4,5)

area(3,4,5)

#multiply
def mux(*args):
  result = 1
  for num in args:
    result *= num
  return result

mux(2,3,4,5)

